### ISSUE TITLE
ACCESS_DENIED

### ISSUE THREAD

**Issue by DaVinciLord** [Node-SMB/marsaud-smb2#18]
I tried to list all the files in a Windows Share but couldn't, the SMB2 object has this value:
connected: false

Here is a fiddle of my code:

```
var SMB2 = require('@marsaud/smb2');
let smb2Client = new SMB2({
  share: '\\\\192.168.17.200\\utilisateurs',
  domain: 'domain',
  username: 'username',
  password: 'password',
  port: 445,
});

smb2Client.readdir('.', (err, files) => {
  if (err) throw err;
  console.log(files);
});

```

And the error stack

```
Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those ac
cess rights.
    at Object.03000000 (/home/davincilord/test/test-smb/node_modules/@marsaud/smb2/lib/tools/message.js:25:21)
    at Socket.<anonymous> (/home/davincilord/test/test-smb/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:72:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by julien-f** [comment]
AFAIK, this library requires all permissions (even admin) on the share, maybe that's the issue?

**Comment by DaVinciLord** [comment]
f

**Comment by DaVinciLord** [comment]
I tested with admin permissions on the share, didn't work either.

**Comment by olivierlambert** [comment]
Can you show exactly the permission panel in your Windows for this share?

IIRC, there is 2 kind of permissions:

* a the share level
* at the FS level

Obviously, one of them is not high enough to allow an access

**Comment by DaVinciLord** [comment]
Tested with a Python script, from linux command line (using mount -t cifs) and with https://github.com/eflexsystems/node-samba-client and both worked (connected and listed files).

I should add that I use a Linux OS.

**Comment by olivierlambert** [comment]
You mean your SMB server is a Linux host?

**Comment by DaVinciLord** [comment]
Nope, the SMB server is on Windows. I just have a Linux client for the SMB (my nodejs application is on a linux server).

**Comment by olivierlambert** [comment]
Okay so take a look at your Windows host, both for NTFS **and** share level permissions.

edit: if we can find the exact permission level that is not necessary to switch on, I think we could ask @marsaud to take a look and fix this (if there is no good reason to ask for those extended permissions)

**Comment by DaVinciLord** [comment]
The Windows Share is indeed in NTFS so I think it's good.
As for the share level permissions, I could only do a screen of this panel:
![capture](https://cloud.githubusercontent.com/assets/11557625/22011262/665eaccc-dc8e-11e6-9b8d-668eafa4b867.PNG)

I use the "Administrateur" account to log in.
