### ISSUE TITLE
Update base

### ISSUE THREAD

**Issue by tracker1** [Node-SMB/marsaud-smb2#22]
Curious if you might consider updating the base requirement to node 8.x?

In this way you can eliminate bluebird and babel from the build and dependency chain... also makes testing against the source easier.  I'm willing to put in the effort and submit a PR.

Note: was going to do this anyway, I'm diagnosing an issue I'm seeing regarding permissions error with ensureDir.  But would rather submit a PR instead of publishing another name-spaced fork.

**Comment by marsaud** [comment]
Yes, go on.

I'll pick up this opportunity to review all opened PRs and then keep a closer eye on this repo.

**Comment by tracker1** [comment]
I've forked downstream from dcyou fork... https://github.com/tracker1/node-smb2

- moved the lib/api/src to lib/api and updated the require and exports to match cjs (for now)
- tweaked the paths so that unix separators can be used
- added support for url string for share/options
- made api interfaces isomorphic returning promises, making callback optional but still supported, no need for separate -promise version
- set engine to node >= 8.5, since iirc that's when async functions are available without a flag.

Need to investigate some issues, as I'm getting ACCESS_DENIED when trying to test for my own use... authentication seems to work okay though.

I can create a branch that has an appropriate package.json, and README.md attached, for direct merge/PR ... not much logic has changed so far.  I've tried to bring in various fixes/adjustments from a few of the forks.

**Comment by gruijter** [comment]
While you are at it. I get an error when trying to writestream to a file that is read-only (which it should). Problem is however that I also get a typeError that crashes my app:
```
 { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.
    at Object.1f000000 (/node_modules/@marsaud/smb2/lib/tools/message.js:25:21)
    at Socket.<anonymous> (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:72:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20) code: 'STATUS_ACCESS_DENIED' }
_stream_readable.js:582
  dest.on('unpipe', onunpipe);
       ^

TypeError: Cannot read property 'on' of undefined
    at ReadStream.Readable.pipe (_stream_readable.js:582:8)
    at ReadStream.fileStream.on (/app.js:176:18)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at fs.js:1992:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```

I'm not an experienced programmer, so probably my code is wrong. This is what I have, but what should I change?
```
	// save a file to a network share via SMB as promise; resolves smb2 filename
	saveSmb(appId) {	// filename is appId
		return new Promise((resolve, reject) => {
			try {
				const filename = `${appId}.zip`;
				this.smb2Client.createWriteStream(filename, (error, smbWriteStream) => {
					if (error) { this.log(error); }
					const fileStream = fs.createReadStream(`./userdata/${appId}.zip`);
					fileStream.on('open', () => {
						// this.log('piping to SMB2');
						fileStream.pipe(smbWriteStream);
					});
					fileStream.on('close', () => {
						// The file has been read completely
						this.log(`${appId}.zip has been saved to SMB2`);
						fileStream.unpipe();
						return resolve(filename);
					});
					fileStream.on('error', (err) => {
						this.log('filestream error: ', err);
						fileStream.unpipe();
						smbWriteStream.end();
					});
				});
			} catch (error) {
				this.error('error:', error);
				this.smb2Client.close();
				this.getsmb2Client();
				return reject(error);
			}
		});
	}
```

**Comment by tracker1** [comment]
@marsaud @julien-f Looks like with the recent adjustments, I think the only thing I added in my fork not here is the support for an `smb://` url string, and normalizing paths...  Going to create 2 separate issues for these. :-)

**Comment by julien-f** [comment]
Thanks!

**Comment by tracker1** [comment]
Actually, looks like the build process is still in place (with a few tweaks, unnecessary for modern node versions)... will try to create a branch this weekend for just that part...

**Comment by julien-f** [comment]
The build process is still here only for `ensureDir` which I did not have the time to rewrite in ES5 yet, as soon as it's done we'll be able to remove it :slightly_smiling_face:

**Comment by tracker1** [comment]
Should be able to just rewrite the import/export statements and remove/replace Bluebird with internal Promises.  :-)  Cool, all the same.  Nice to see complexity come out.
