### ISSUE TITLE
npm released version 0.13 does not support overwriting existing files with stream

### ISSUE THREAD

**Issue by gruijter** [Node-SMB/marsaud-smb2#40]
Error when trying to do smb2Client.createWriteStream on an already existing file. According to the documentation it should just overwrite without error.
```
{ Error: STATUS_OBJECT_NAME_COLLISION (0xC0000035) : The object name already exists.
    at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15)
    at module.exports.createWriteStream (/node_modules/@marsaud/smb2/lib/api/createWriteStream.js:77:5)
    at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21
    at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8
    at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25
    at Object.<anonymous> (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15)
    at Socket.<anonymous> (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  messageName: 'create',
```

**Comment by julien-f** [comment]
Just pass a `flags: 'w'` in the option, it will allow you to overwrite the file.

**Comment by gruijter** [comment]
Ok, thx. Will try that. Is that documented somewhere?

**Comment by gruijter** [comment]
Never mind. Just found the link with flag documentation :)
