### ISSUE TITLE
STATUS_NOT_SUPPORTED (0xC00000BB) : The request is not supported.

### ISSUE THREAD

**Issue by nnduc1994** [Node-SMB/marsaud-smb2#77]
[Got the same issue with the node-smb2 package as well]
Got this message when trying to connect to smb server that I don't have access to 
The code so far 
```
   smb2Client = new SMB2Original({
      share: '\\\\00.00.00.00\\abc_export$',
      domain: 'domain',
      username: 'user',
      password: 'pwd',
    });


    smb2Client.readdir('\\', (err, files) => {
      if (err) throw err;
      console.log(files);
    });
```

Error object: 

```
{
    "errorType": "Error",
    "errorMessage": "STATUS_NOT_SUPPORTED (0xC00000BB) : The request is not supported.",
    "code": "STATUS_NOT_SUPPORTED",
    "stack": [
        "Error: STATUS_NOT_SUPPORTED (0xC00000BB) : The request is not supported.",
        "    at Object.01000000 (/var/task/node_modules/smb2/lib/tools/message.js:25:21)",
        "    at Socket.<anonymous> (/var/task/node_modules/smb2/lib/tools/smb2-forge.js:72:31)",
        "    at Socket.emit (events.js:315:20)",
        "    at addChunk (internal/streams/readable.js:309:12)",
        "    at readableAddChunk (internal/streams/readable.js:284:9)",
        "    at Socket.Readable.push (internal/streams/readable.js:223:10)",
        "    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"
    ]
}
```

[Edited: I saw another issue with the same code, but can't find the answer from that issue either. Sorry for sort of spamming ]

**Comment by siddiq-rehman** [comment]
Any update on this one?

**Comment by julien-f** [comment]
Hello, this lib is currently looking for maintainers, please take a look at #79

**Comment by blackw1ng** [comment]
I am also experiencing this on connecting to a share on a Windows7 computer...
https://docs.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/request-not-supported-smb-data-deduplication suggests that it may be related to the `SMB Read AndX Request` in conjunction with 
`HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters\enableecp = 1`
